name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: getargv.py/dist/*
          name: ${{ steps.bump_version.outputs.new_version }}
          tag_name: ${{ steps.bump_version.outputs.new_version }}
