name: Eleventy Build
on: [push]
permissions:
  contents: write

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - run: ls
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          path: './public'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "release.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ steps.date.outputs.date }}
            makeLatest: true
      - name: Update Server
        run: curl -X POST --insecure https://www.fsae.caltech.edu/github.php
