name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - run: ls
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          path: './public'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "release.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
